### ISSUE TITLE
Various memory management issues

### ISSUE THREAD

**Issue by artomal** [clear-code/xmlua#24]
Hi there,

I've been testing this library and playing with a different operations and noticed a problem with memory management once you start playing with elements and combining them together. I used the script below to reproduce the issue:

```
local xmlua = require("xmlua")

local function add_child(parent, child)
  return parent:add_child(child)
end

local function create_element(name, attributes)
  local elm = xmlua.XML.build({ name }):root()

  if attributes then
    for att_name, val in pairs(attributes) do
      elm:set_attribute(att_name, val)
    end
  end

  return elm:unlink()
end

for i=1,5000 do
  local a = create_element("a", {
    ["a1"] = "a1-test",
    ["a2"]  = "a2-test"
  })

  local b = create_element("b", {
    ["b1"] = "b1-test",
    ["b2"]  = "b2-test"
  })

  add_child(a, b)
  print("[i] " .. i .. " " .. a:to_xml())
end
```

The script doesn't even finish and errors at 2xx, 3xx iteration I get a different memory related error messages for instance:

```malloc_consolidate(): invalid chunk size```

or:

```free(): invalid pointer```

Any ideas what might be happening? Maybe I use illegal API operations which introduce these type of problems?

**Comment by kou** [comment]
Thanks for your report.
I've fixed it.

**Comment by artomal** [comment]
Hi @kou , thanks for a quick response, it seems that issue is still persist and it is only partially resolved, if you would run this script a couple of times it sometimes finished and sometimes it exits without any error but if you look at exit code with `echo $?` I see it is `1`

`
...
<b b2="b2-test" b1="b1-test"/>
</a>
[i] 476 <a a1="a1-test" a2="a2-test">
  <b b2="b2-test" b1="b1-test"/>
</a>
[i] 477 <a a1="a1-test" a2="a2-test">
  <b b2="b2-test" b1="b1-test"/>
</a>
[i] 478 <a a1="a1-test" a2="a2-test">
  <b b2="b2-test" b1="b1-test"/>
</a>
[i] 479 <a a1="a1-test" a2="a2-test">
  <b b2="b2-test" b1="b1-test"/>
</a>
$ echo $?
$ 11
`

**Comment by artomal** [comment]
I think the problem happens when you have two unlinked elements and combine them together using `add_child()`.

**Comment by kou** [comment]
Could you try master?

**Comment by artomal** [comment]
It seems now it is fixed, thanks @kou !
